package transcript

import "testing"

// ★★★ **하네스 글은 빼고 그 글을 인용한 대화는 살린다.**
//
// 이 파일이 못 박는 것은 앵커링이다. 부분 문자열로 걸렀으면 정상 대화 6건이
// 통째로 사라졌다 — 실측(2026-08-31): `API Error:` 가 나오는 발화 22건 중 5건이
// 그 에러를 **분석하는** 대화였고, `<command-name>` 은 46건 중 1건이 그랬다.
func TestHarnessTextNeedsThePrefix(t *testing.T) {
	harness := []string{
		"API Error: Opus 5 (1M context)'s safeguards flagged this message (https://www.anthropic.com/legal/aup).",
		"<command-name>/effort</command-name>\n<command-message>effort</command-message>",
		"<local-command-stdout>Set effort level to max</local-command-stdout>",
		"<local-command-caveat>Caveat: The messages below were generated by the user</local-command-caveat>",
		// 앞에 줄바꿈·공백이 붙어도 걸러야 한다 — 그것 하나로 무력해지면 안 된다.
		"\n\n  API Error: 무언가",
	}
	for _, s := range harness {
		if !IsHarnessText(s) {
			t.Errorf("하네스 글을 못 걸렀다: %.60q", s)
		}
	}

	// ★ **인용은 대화다.** 아래가 전부 실제 트랜스크립트에서 온 모양이다.
	conversation := []string{
		"차단이 왜 나는지 봤는데 API Error: 로 시작하는 줄이 어시스턴트 발화로 저장되더라",
		"느려지지 않습니다 — 훅은 `<command-name>` 같은 에코를 발화로 세고 있었습니다",
		`{"tier":"worklog","summary":"API Error: 관련 원인을 측정으로 확인"}`,
		"이 표지가 왜 필요한지 설명하면, <local-command-stdout> 은 하네스가 만든 것이다",
		"",
		"   ",
		"평범한 대화다",
	}
	for _, s := range conversation {
		if IsHarnessText(s) {
			t.Errorf("정상 대화를 하네스로 오판했다: %.70q", s)
		}
	}
}

// 표지를 낱개로 늘리면 위 계약이 깨진다 — `safeguards flagged` 를 단독 표지로
// 넣으면 그것을 논하는 문장이 전부 발화에서 빠진다. 그 글은 언제나 `API Error:`
// 로 시작하는 같은 블록의 일부이므로 표지 하나로 충분하다.
func TestHarnessMarkersStayNarrow(t *testing.T) {
	for _, p := range harnessPrefixes {
		if p == "safeguards flagged" || p == "Request ID: req_" {
			t.Errorf("%q 는 표지로 두면 안 된다 — 인용을 죽인다", p)
		}
	}
	if len(harnessPrefixes) == 0 {
		t.Fatal("표지가 비었다 — 필터가 아무것도 안 한다")
	}
}
